### ISSUE TITLE
Incompatibility with MemoryLeakFix

### ISSUE THREAD

**Issue by ConqAra** [MrMelon54/compact-ui-fabric#1]
Crashes when ran with [MemoryLeakFix](https://modrinth.com/mod/memoryleakfix)

Log: [https://pastebin.com/K9LuwBjR](https://pastebin.com/K9LuwBjR)

**Comment by mrmelon54** [comment]
the pastebin doesn't exist

**Comment by ConqAra** [comment]
uh ok they literally just removed my pastebin? anyways [https://paste.ee/p/Fov3G](https://paste.ee/p/Fov3G)

**Comment by CodeF53** [comment]
can confirm:
memory leak fix and compact ui
https://mclo.gs/fmCOg7J

just compact ui
https://mclo.gs/zZVB0cl

**Comment by mrmelon54** [comment]
I seem to be unable to reproduce this

**Comment by ConqAra** [comment]
what java version are you using? I am using JAVA 18

**Comment by mrmelon54** [comment]
I am using java 17

**Comment by mrmelon54** [comment]
I am unable to reproduce so I will close this issue for now.. if you can reproduce then feel free to open the issue again

**Comment by ghost** [comment]
Hey, I'm also getting this same issue. https://pastebin.com/AX3YaCdz

- Compact UI 1.19 3.0.1 build 10 (latest)
- MemoryLeakFix 1.19.1 0.7.0 (latest)
- Minecraft 1.19.2
- Quilt Loader 0.17.3
- Java 17

**Comment by mrmelon54** [comment]
Report on https://github.com/mrmelon54/compact_ui if the issue still occurs in 1.20 versions
