### ISSUE TITLE
Game completely crashes upon clicking any of the compacted buttons

### ISSUE THREAD

**Issue by ConqAra** [MrMelon54/compact-ui-fabric#3]
When clicking singleplayer, resourcepacks, or multiplayer the game immediately crashes with compact ui installed.
I have no idea how this is happening, I only have compact ui and fabric api installed.

Log: [https://paste.ee/p/FsaMk](https://paste.ee/p/FsaMk)

**Comment by mrmelon54** [comment]
try using java 17?

**Comment by mrmelon54** [comment]
I can't reproduce this.. if you can feel free to reopen the issue..

**Comment by ghost** [comment]
I'm also getting this same issue. https://pastebin.com/bnA3LqVj

- Compact UI 1.19 3.0.1 build 10 (latest)
- Minecraft 1.19.2
- Quilt Loader 0.17.3
- Java 17

**Comment by mrmelon54** [comment]
Duplicate of #1
