### ISSUE TITLE
[Compatibility] MC Folders

### ISSUE THREAD

**Issue by MrKacafirekCZ** [MrMelon54/compact-ui-fabric#6]
Currently this mod crashes with MC Folders.

Opposite issue [here](https://github.com/MrKacafirekCZ/mcfolders/issues/4)

**Comment by mrmelon54** [comment]
omg lol
enhanced searchability and compact ui and incompatible with mc folders :rofl:

**Comment by mrmelon54** [comment]
Report on https://github.com/mrmelon54/compact_ui if this is still incompatible in 1.20
